# Generated by Django 2.1.5 on 2020-05-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jiancheng',
            fields=[
                ('data_x', models.IntegerField(db_column='Data_X')),
                ('data_y', models.IntegerField(db_column='Data_Y')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'jiancheng',
                'managed': False,
            },
        ),
    ]
